set_property SRC_FILE_INFO {cfile:{C:/Users/danbe/Desktop/DSP Projects/VivadoPrac/Getting Back Into It/Getting Back Into It.srcs/constrs_1/new/AND_Gate.xdc} rfile:{../../../Getting Back Into It.srcs/constrs_1/new/AND_Gate.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {A}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {B}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {outAND}]
